Release
AlexForJava/HomeWork9 pull request #1
Opened 2019-03-23 19:08 UTC by AlexForJava

2019-03-23 22:37 UTC, Taniann requested changes
good, but make a little fixing please

2019-03-23 22:37 UTC, Taniann commented on src/main/java/com/gmail/chernii/oleksii/list/MyArrayList.java
> +    private static final int DEFAULT_LENGTH = 10;
firstly declare static field, then non-static
[Ordering of class contents](https://mate-academy.github.io/style-guides/java/java.html#s3.4.2-ordering-class-contents)

2019-03-23 22:37 UTC, Taniann commented on src/test/java/com/gmail/chernii/oleksii/list/MyArrayListTest.java
> +        list = new MyArrayList<String>();
use diamond operator

2019-03-23 22:37 UTC, Taniann commented on src/test/java/com/gmail/chernii/oleksii/list/MyLinkedListTest.java
> +        list = new MyLinkedList<String>();
thw same about diamond operator

2019-03-23 22:39 UTC, Taniann commented on src/test/java/com/gmail/chernii/oleksii/list/MyLinkedListTest.java
> +import static org.junit.Assert.*;
dont use wild card import

2019-03-23 22:39 UTC, Taniann commented on src/test/java/com/gmail/chernii/oleksii/stack/MyStackTest.java
> +import static org.junit.Assert.*;
the same

2019-03-24 19:50 UTC, Taniann approved these changes
good

2019-03-24 20:45 UTC, AlexForJava commented
😉

24 марта 2019, 21:50:30, от "Алексей" <hqq@ukr.net>:

@Taniann approved this pull request.

good

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-05-16 16:23 UTC, merged